[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Ecophys = "19467474-d12d-47c9-939f-3e50fbfd93ad"
PlantGeomPrimitives = "7eef3cc5-4580-4ff0-8f6f-933507db6664"
PlantGeomTurtle = "7d6e2781-1c99-4c66-97ec-106669f3e96e"
PlantGraphs = "615ad455-9aac-4340-9247-71ef610f781a"
PlantRayTracer = "78485975-e4aa-407d-b3bb-ded5a4265d05"
PlantSimEngine = "9a576370-710b-4269-adf9-4f603a9c6423"
PlantViz = "358bd95d-d12c-439f-94b7-04b17e500c7f"
SkyDomes = "1838625c-7cf7-40c6-898b-904883e4b556"
VPLDocs = "19246b20-85cd-4f94-a989-28bb6828320f"
VirtualPlantLab = "b977ecfa-1b9a-418d-909d-4ebe565736ce"

[compat]
Ecophys = "0.1.1"
PlantGeomPrimitives = "0.1.1"
PlantGeomTurtle = "0.1.1"
PlantGraphs = "0.1.3"
PlantRayTracer = "0.1.1"
PlantSimEngine = "0.13.2"
PlantViz = "0.1.1"
SkyDomes = "0.1.9"
VirtualPlantLab = "0.1.2"
julia = "1.12"
